/*
 * Dentons KMN ERP
 * Copyright (c) 2026 Bouquet Innovation SA. All rights reserved.
 * Proprietary and confidential. Unauthorised copying, distribution, modification,
 * or use of this file, via any medium, is strictly prohibited.
 */
// Turn a Markdown-subset document (what Pinto produces) into a downloadable
// DOCX or PDF. Pure-JS (docx + pdf-lib, standard fonts) so it runs on Vercel
// serverless with no native binaries or bundled font files.
import "server-only";
import {
  Document,
  Packer,
  Paragraph,
  TextRun,
  HeadingLevel,
  AlignmentType,
  Footer,
  PageBreak,
} from "docx";
import { PDFDocument, StandardFonts, rgb, type PDFFont, type PDFPage } from "pdf-lib";

export interface GeneratedDoc {
  title: string;
  subtitle?: string;
  markdown: string;
  /** Footer repeated on every page. Defaults to the Pinto disclaimer. */
  footer?: string;
  /**
   * Tighter typography. Attestations are expected to be one page per language:
   * a signature block that lands on a sheet of its own reads as an incomplete
   * document at a consular counter.
   */
  compact?: boolean;
}

type Block =
  | { kind: "h"; level: 1 | 2 | 3; text: string }
  | { kind: "p"; text: string }
  | { kind: "li"; text: string; ordered: boolean }
  | { kind: "pagebreak" };

/** Marker a caller puts on its own line to force a new page. */
export const PAGE_BREAK_MARKER = "[[PAGEBREAK]]";

// Parse the limited Markdown Pinto emits: #/##/### headings, - or * bullets,
// "1." ordered items, everything else a paragraph. Blank lines separate blocks.
function parse(markdown: string): Block[] {
  const blocks: Block[] = [];
  for (const raw of markdown.replace(/\r\n/g, "\n").split("\n")) {
    const line = raw.trim();
    if (!line) continue;
    let m: RegExpMatchArray | null;
    if (line === PAGE_BREAK_MARKER) {
      blocks.push({ kind: "pagebreak" });
    } else if ((m = line.match(/^(#{1,3})\s+(.*)$/))) {
      blocks.push({ kind: "h", level: m[1].length as 1 | 2 | 3, text: m[2].trim() });
    } else if ((m = line.match(/^[-*]\s+(.*)$/))) {
      blocks.push({ kind: "li", text: m[1].trim(), ordered: false });
    } else if ((m = line.match(/^\d+[.)]\s+(.*)$/))) {
      blocks.push({ kind: "li", text: m[1].trim(), ordered: true });
    } else {
      blocks.push({ kind: "p", text: line });
    }
  }
  return blocks;
}

// Split a string on **bold** markers into segments.
function segments(text: string): { text: string; bold: boolean }[] {
  const out: { text: string; bold: boolean }[] = [];
  const re = /\*\*(.+?)\*\*/g;
  let last = 0;
  let m: RegExpExecArray | null;
  while ((m = re.exec(text))) {
    if (m.index > last) out.push({ text: text.slice(last, m.index), bold: false });
    out.push({ text: m[1], bold: true });
    last = m.index + m[0].length;
  }
  if (last < text.length) out.push({ text: text.slice(last), bold: false });
  return out.length ? out : [{ text, bold: false }];
}

const FOOTER =
  "Generated by Pinto for Dentons KMN — general information, verify against the official text and have a qualified lawyer review.";

// The PDF path embeds the standard Helvetica faces, which are limited to
// WinAnsi (CP1252). French copy stays well inside that set, but a stray
// character pasted from elsewhere (a narrow no-break space, a Greek letter)
// would otherwise make pdf-lib throw mid-render, so map what we can and drop
// the rest rather than fail the download.
const CP1252_EXTRA = new Set(
  "€‚ƒ„…†‡ˆ‰Š‹ŒŽ‘’“”•–—˜™š›œžŸ".split(""),
);

const CP1252_FOLD: Record<string, string> = {
  "\u202F": "\u00A0", // narrow no-break space -> no-break space
  "\u2009": " ", // thin space
  "\u200B": "", // zero-width space
  "\uFEFF": "", // byte-order mark
  "\u00AD": "", // soft hyphen
  "\u2212": "-", // minus sign
  "\u2044": "/", // fraction slash
};

function winAnsi(text: string): string {
  let out = "";
  for (const ch of text) {
    const folded = CP1252_FOLD[ch];
    const c = folded === undefined ? ch : folded;
    for (const k of c) {
      const code = k.codePointAt(0)!;
      if (code === 0x0a || code === 0x0d) continue;
      if ((code >= 0x20 && code <= 0x7e) || (code >= 0xa0 && code <= 0xff) || CP1252_EXTRA.has(k)) {
        out += k;
      }
      // Anything else is silently dropped: never render a mojibake glyph on an
      // official document.
    }
  }
  return out;
}

export async function buildDocx(doc: GeneratedDoc): Promise<Buffer> {
  const gap = doc.compact ? 80 : 120;
  const headBefore = doc.compact ? 140 : 200;
  const children: Paragraph[] = [
    new Paragraph({
      alignment: AlignmentType.CENTER,
      spacing: { after: doc.subtitle ? 60 : 240 },
      children: [new TextRun({ text: doc.title, bold: true, size: 40 })],
    }),
  ];
  if (doc.subtitle) {
    children.push(
      new Paragraph({
        alignment: AlignmentType.CENTER,
        spacing: { after: 240 },
        children: [new TextRun({ text: doc.subtitle, italics: true, size: 22, color: "555555" })],
      }),
    );
  }

  for (const b of parse(doc.markdown)) {
    if (b.kind === "pagebreak") {
      children.push(new Paragraph({ children: [new PageBreak()] }));
    } else if (b.kind === "h") {
      children.push(
        new Paragraph({
          heading:
            b.level === 1 ? HeadingLevel.HEADING_1 : b.level === 2 ? HeadingLevel.HEADING_2 : HeadingLevel.HEADING_3,
          spacing: { before: headBefore, after: 80 },
          children: segments(b.text).map((s) => new TextRun({ text: s.text, bold: true })),
        }),
      );
    } else if (b.kind === "li") {
      children.push(
        new Paragraph({
          bullet: { level: 0 },
          spacing: { after: 40 },
          children: segments(b.text).map((s) => new TextRun({ text: s.text, bold: s.bold })),
        }),
      );
    } else {
      children.push(
        new Paragraph({
          spacing: { after: gap },
          children: segments(b.text).map((s) => new TextRun({ text: s.text, bold: s.bold })),
        }),
      );
    }
  }

  const document = new Document({
    creator: "Pinto — Dentons KMN",
    title: doc.title,
    sections: [
      {
        properties: {},
        footers: {
          default: new Footer({
            children: [
              new Paragraph({
                alignment: AlignmentType.CENTER,
                children: [new TextRun({ text: doc.footer ?? FOOTER, size: 14, color: "888888" })],
              }),
            ],
          }),
        },
        children,
      },
    ],
  });
  return Buffer.from(await Packer.toBuffer(document));
}

export async function buildPdf(doc: GeneratedDoc): Promise<Buffer> {
  const compact = !!doc.compact;
  const bodySize = compact ? 10 : 10.5;
  const leading = compact ? 3.5 : 4;
  const paraGap = compact ? 3 : 6;
  const headGap = compact ? 4 : 6;

  const pdf = await PDFDocument.create();
  const font = await pdf.embedFont(StandardFonts.Helvetica);
  const bold = await pdf.embedFont(StandardFonts.HelveticaBold);
  const italic = await pdf.embedFont(StandardFonts.HelveticaOblique);

  const W = 595.28;
  const H = 841.89;
  const M = compact ? 48 : 56;
  const maxW = W - M * 2;
  const gray = rgb(0.53, 0.53, 0.53);

  let page: PDFPage = pdf.addPage([W, H]);
  let y = H - M;

  const footerText = winAnsi(doc.footer ?? FOOTER);

  const drawFooter = (pg: PDFPage) => {
    const size = 7;
    const lines = wrap(footerText, font, size, maxW);
    let fy = M - 14;
    for (const ln of lines) {
      pg.drawText(ln, { x: M, y: fy, size, font, color: gray });
      fy -= size + 2;
    }
  };

  const newPage = () => {
    drawFooter(page);
    page = pdf.addPage([W, H]);
    y = H - M;
  };

  const ensure = (needed: number) => {
    if (y - needed < M + 24) newPage();
  };

  const writeLine = (text: string, f: PDFFont, size: number, indent = 0, color = rgb(0, 0, 0)) => {
    for (const ln of wrap(text, f, size, maxW - indent)) {
      ensure(size + leading);
      page.drawText(ln, { x: M + indent, y, size, font: f, color });
      y -= size + leading;
    }
  };

  // Title + subtitle, centred.
  const titleSize = compact ? 17 : 20;
  for (const ln of wrap(winAnsi(doc.title), bold, titleSize, maxW)) {
    ensure(titleSize + 6);
    const w = bold.widthOfTextAtSize(ln, titleSize);
    page.drawText(ln, { x: (W - w) / 2, y, size: titleSize, font: bold });
    y -= titleSize + 6;
  }
  if (doc.subtitle) {
    const s = 11;
    for (const ln of wrap(winAnsi(doc.subtitle), italic, s, maxW)) {
      ensure(s + 4);
      const w = italic.widthOfTextAtSize(ln, s);
      page.drawText(ln, { x: (W - w) / 2, y, size: s, font: italic, color: gray });
      y -= s + 4;
    }
  }
  y -= compact ? 8 : 12;

  for (const b of parse(doc.markdown)) {
    if (b.kind === "pagebreak") {
      newPage();
    } else if (b.kind === "h") {
      const base = b.level === 1 ? 15 : b.level === 2 ? 13 : 11.5;
      const size = compact ? base - 1.5 : base;
      y -= headGap;
      writeLine(strip(b.text), bold, size);
      y -= compact ? 1 : 2;
    } else if (b.kind === "li") {
      writeLine("•  " + strip(b.text), font, bodySize, 10);
      y -= 2;
    } else {
      // A paragraph wrapped end-to-end in ** is emphasised as a whole (an
      // addressee line, a signatory's name); mixed emphasis falls back to plain.
      const whole = b.text.match(/^\*\*(.+)\*\*$/);
      writeLine(strip(b.text), whole && !whole[1].includes("**") ? bold : font, bodySize);
      y -= paraGap;
    }
  }
  drawFooter(page);

  return Buffer.from(await pdf.save());
}

// Remove **bold** markers and drop anything the standard fonts cannot encode.
function strip(text: string): string {
  return winAnsi(text.replace(/\*\*(.+?)\*\*/g, "$1"));
}

// Greedy word-wrap to a pixel width for a given font/size. Only ordinary
// whitespace is a break opportunity — a no-break space (thousands separator in
// French amounts) deliberately holds its group on one line.
function wrap(text: string, font: PDFFont, size: number, width: number): string[] {
  const words = text.split(/[ \t\r\n]+/).filter(Boolean);
  const lines: string[] = [];
  let cur = "";
  for (const word of words) {
    const trial = cur ? cur + " " + word : word;
    if (font.widthOfTextAtSize(trial, size) > width && cur) {
      lines.push(cur);
      cur = word;
    } else {
      cur = trial;
    }
  }
  if (cur) lines.push(cur);
  return lines.length ? lines : [""];
}
