// Turn a Markdown-subset document (what Pinto produces) into a downloadable
// DOCX or PDF. Pure-JS (docx + pdf-lib, standard fonts) so it runs on Vercel
// serverless with no native binaries or bundled font files.
import "server-only";
import {
  Document,
  Packer,
  Paragraph,
  TextRun,
  HeadingLevel,
  AlignmentType,
  Footer,
} from "docx";
import { PDFDocument, StandardFonts, rgb, type PDFFont, type PDFPage } from "pdf-lib";

export interface GeneratedDoc {
  title: string;
  subtitle?: string;
  markdown: string;
}

type Block =
  | { kind: "h"; level: 1 | 2 | 3; text: string }
  | { kind: "p"; text: string }
  | { kind: "li"; text: string; ordered: boolean };

// Parse the limited Markdown Pinto emits: #/##/### headings, - or * bullets,
// "1." ordered items, everything else a paragraph. Blank lines separate blocks.
function parse(markdown: string): Block[] {
  const blocks: Block[] = [];
  for (const raw of markdown.replace(/\r\n/g, "\n").split("\n")) {
    const line = raw.trim();
    if (!line) continue;
    let m: RegExpMatchArray | null;
    if ((m = line.match(/^(#{1,3})\s+(.*)$/))) {
      blocks.push({ kind: "h", level: m[1].length as 1 | 2 | 3, text: m[2].trim() });
    } else if ((m = line.match(/^[-*]\s+(.*)$/))) {
      blocks.push({ kind: "li", text: m[1].trim(), ordered: false });
    } else if ((m = line.match(/^\d+[.)]\s+(.*)$/))) {
      blocks.push({ kind: "li", text: m[1].trim(), ordered: true });
    } else {
      blocks.push({ kind: "p", text: line });
    }
  }
  return blocks;
}

// Split a string on **bold** markers into segments.
function segments(text: string): { text: string; bold: boolean }[] {
  const out: { text: string; bold: boolean }[] = [];
  const re = /\*\*(.+?)\*\*/g;
  let last = 0;
  let m: RegExpExecArray | null;
  while ((m = re.exec(text))) {
    if (m.index > last) out.push({ text: text.slice(last, m.index), bold: false });
    out.push({ text: m[1], bold: true });
    last = m.index + m[0].length;
  }
  if (last < text.length) out.push({ text: text.slice(last), bold: false });
  return out.length ? out : [{ text, bold: false }];
}

const FOOTER =
  "Generated by Pinto for Dentons KMN — general information, verify against the official text and have a qualified lawyer review.";

export async function buildDocx(doc: GeneratedDoc): Promise<Buffer> {
  const children: Paragraph[] = [
    new Paragraph({
      alignment: AlignmentType.CENTER,
      spacing: { after: doc.subtitle ? 60 : 240 },
      children: [new TextRun({ text: doc.title, bold: true, size: 40 })],
    }),
  ];
  if (doc.subtitle) {
    children.push(
      new Paragraph({
        alignment: AlignmentType.CENTER,
        spacing: { after: 240 },
        children: [new TextRun({ text: doc.subtitle, italics: true, size: 22, color: "555555" })],
      }),
    );
  }

  for (const b of parse(doc.markdown)) {
    if (b.kind === "h") {
      children.push(
        new Paragraph({
          heading:
            b.level === 1 ? HeadingLevel.HEADING_1 : b.level === 2 ? HeadingLevel.HEADING_2 : HeadingLevel.HEADING_3,
          spacing: { before: 200, after: 80 },
          children: segments(b.text).map((s) => new TextRun({ text: s.text, bold: true })),
        }),
      );
    } else if (b.kind === "li") {
      children.push(
        new Paragraph({
          bullet: { level: 0 },
          spacing: { after: 40 },
          children: segments(b.text).map((s) => new TextRun({ text: s.text, bold: s.bold })),
        }),
      );
    } else {
      children.push(
        new Paragraph({
          spacing: { after: 120 },
          children: segments(b.text).map((s) => new TextRun({ text: s.text, bold: s.bold })),
        }),
      );
    }
  }

  const document = new Document({
    creator: "Pinto — Dentons KMN",
    title: doc.title,
    sections: [
      {
        properties: {},
        footers: {
          default: new Footer({
            children: [
              new Paragraph({
                alignment: AlignmentType.CENTER,
                children: [new TextRun({ text: FOOTER, size: 14, color: "888888" })],
              }),
            ],
          }),
        },
        children,
      },
    ],
  });
  return Buffer.from(await Packer.toBuffer(document));
}

export async function buildPdf(doc: GeneratedDoc): Promise<Buffer> {
  const pdf = await PDFDocument.create();
  const font = await pdf.embedFont(StandardFonts.Helvetica);
  const bold = await pdf.embedFont(StandardFonts.HelveticaBold);
  const italic = await pdf.embedFont(StandardFonts.HelveticaOblique);

  const W = 595.28;
  const H = 841.89;
  const M = 56;
  const maxW = W - M * 2;
  const gray = rgb(0.53, 0.53, 0.53);

  let page: PDFPage = pdf.addPage([W, H]);
  let y = H - M;

  const drawFooter = (pg: PDFPage) => {
    const size = 7;
    const lines = wrap(FOOTER, font, size, maxW);
    let fy = M - 14;
    for (const ln of lines) {
      pg.drawText(ln, { x: M, y: fy, size, font, color: gray });
      fy -= size + 2;
    }
  };

  const newPage = () => {
    drawFooter(page);
    page = pdf.addPage([W, H]);
    y = H - M;
  };

  const ensure = (needed: number) => {
    if (y - needed < M + 24) newPage();
  };

  const writeLine = (text: string, f: PDFFont, size: number, indent = 0, color = rgb(0, 0, 0)) => {
    for (const ln of wrap(text, f, size, maxW - indent)) {
      ensure(size + 4);
      page.drawText(ln, { x: M + indent, y, size, font: f, color });
      y -= size + 4;
    }
  };

  // Title + subtitle, centred.
  const titleSize = 20;
  for (const ln of wrap(doc.title, bold, titleSize, maxW)) {
    ensure(titleSize + 6);
    const w = bold.widthOfTextAtSize(ln, titleSize);
    page.drawText(ln, { x: (W - w) / 2, y, size: titleSize, font: bold });
    y -= titleSize + 6;
  }
  if (doc.subtitle) {
    const s = 11;
    for (const ln of wrap(doc.subtitle, italic, s, maxW)) {
      ensure(s + 4);
      const w = italic.widthOfTextAtSize(ln, s);
      page.drawText(ln, { x: (W - w) / 2, y, size: s, font: italic, color: gray });
      y -= s + 4;
    }
  }
  y -= 12;

  for (const b of parse(doc.markdown)) {
    if (b.kind === "h") {
      const size = b.level === 1 ? 15 : b.level === 2 ? 13 : 11.5;
      y -= 6;
      writeLine(strip(b.text), bold, size);
      y -= 2;
    } else if (b.kind === "li") {
      writeLine("•  " + strip(b.text), font, 10.5, 10);
      y -= 2;
    } else {
      writeLine(strip(b.text), font, 10.5);
      y -= 6;
    }
  }
  drawFooter(page);

  return Buffer.from(await pdf.save());
}

// Remove **bold** markers for the flat PDF renderer.
function strip(text: string): string {
  return text.replace(/\*\*(.+?)\*\*/g, "$1");
}

// Greedy word-wrap to a pixel width for a given font/size.
function wrap(text: string, font: PDFFont, size: number, width: number): string[] {
  const words = text.split(/\s+/).filter(Boolean);
  const lines: string[] = [];
  let cur = "";
  for (const word of words) {
    const trial = cur ? cur + " " + word : word;
    if (font.widthOfTextAtSize(trial, size) > width && cur) {
      lines.push(cur);
      cur = word;
    } else {
      cur = trial;
    }
  }
  if (cur) lines.push(cur);
  return lines.length ? lines : [""];
}
