/*
 * Dentons KMN ERP
 * Copyright (c) 2026 Bouquet Innovation SA. All rights reserved.
 * Proprietary and confidential. Unauthorised copying, distribution, modification,
 * or use of this file, via any medium, is strictly prohibited.
 */
// Bilingual (EN + FR) HR document engine.
//
// Attestations, mission orders and invitation letters produced here are read by
// embassies, consulates and immigration services, so the wording is fixed in
// templates rather than generated by a model: the same input must always yield
// the same text, in both languages, with nothing invented. The module is
// isomorphic (no server-only imports) so the form can validate and preview
// locally before anything is issued.

// --- Field metadata ------------------------------------------------------

export type HrFieldKind = "text" | "date" | "money" | "textarea" | "select";

export interface HrSelectOption {
  value: string;
  en: string;
  fr: string;
}

export interface HrDocField {
  key: string;
  en: string;
  fr: string;
  kind: HrFieldKind;
  required: boolean;
  options?: HrSelectOption[];
  /**
   * Free text that reads as English prose. The form offers a companion
   * `<key>_fr` input so the French version is professionally equivalent rather
   * than an English fragment dropped into French sentences; when it is left
   * empty the English value is reused.
   */
  translatable?: boolean;
  /** Pre-filled when the officer opens the form. */
  default?: string;
  /** Grouping hint for the form layout. */
  group: "subject" | "details" | "issuance" | "signatory";
  /** Render the input full width. */
  wide?: boolean;
}

export const ORGANISATION = "Dentons KMN";
export const DEFAULT_ADDRESS = "Immeuble Abricam, Santa Barbara Bonamousadi, Douala, Cameroon";
export const DEFAULT_ADDRESS_FR = "Immeuble Abricam, Santa Barbara Bonamousadi, Douala, Cameroun";
export const DEFAULT_PLACE = "Douala";

const HONORIFICS: HrSelectOption[] = [
  { value: "MR", en: "Mr", fr: "M." },
  { value: "MS", en: "Ms", fr: "Mme" },
  { value: "MRS", en: "Mrs", fr: "Mme" },
  { value: "DR", en: "Dr", fr: "Dr" },
  { value: "PROF", en: "Prof.", fr: "Pr" },
  { value: "ME", en: "Me", fr: "Me" },
];

const ID_TYPES: HrSelectOption[] = [
  { value: "PASSPORT", en: "passport", fr: "passeport" },
  { value: "NATIONAL_ID", en: "national identity card", fr: "carte nationale d'identité" },
  { value: "RESIDENCE_PERMIT", en: "residence permit", fr: "carte de séjour" },
];

const EMPLOYMENT_STATUSES: HrSelectOption[] = [
  { value: "PERMANENT", en: "an open-ended (permanent) contract", fr: "un contrat à durée indéterminée" },
  { value: "FIXED_TERM", en: "a fixed-term contract", fr: "un contrat à durée déterminée" },
  { value: "FULL_TIME", en: "a full-time contract", fr: "un contrat à temps plein" },
  { value: "PART_TIME", en: "a part-time contract", fr: "un contrat à temps partiel" },
  { value: "CONSULTANT", en: "a consultancy agreement", fr: "un contrat de prestation de services" },
  { value: "PROBATION", en: "a probationary engagement", fr: "un contrat à l'essai" },
];

const LEAVE_TYPES: HrSelectOption[] = [
  { value: "ANNUAL", en: "annual leave", fr: "congé annuel" },
  { value: "SICK", en: "sick leave", fr: "congé de maladie" },
  { value: "MATERNITY", en: "maternity leave", fr: "congé de maternité" },
  { value: "PATERNITY", en: "paternity leave", fr: "congé de paternité" },
  { value: "UNPAID", en: "unpaid leave", fr: "congé sans solde" },
  { value: "EXCEPTIONAL", en: "exceptional leave", fr: "congé exceptionnel" },
  { value: "COMPASSIONATE", en: "compassionate leave", fr: "congé pour événement familial" },
];

const CURRENCIES: HrSelectOption[] = [
  { value: "XAF", en: "CFA francs (XAF)", fr: "francs CFA (XAF)" },
  { value: "EUR", en: "euros (EUR)", fr: "euros (EUR)" },
  { value: "USD", en: "US dollars (USD)", fr: "dollars américains (USD)" },
  { value: "GBP", en: "pounds sterling (GBP)", fr: "livres sterling (GBP)" },
];

const PAY_FREQUENCIES: HrSelectOption[] = [
  { value: "MONTHLY", en: "monthly", fr: "mensuelle" },
  { value: "FORTNIGHTLY", en: "fortnightly", fr: "bimensuelle" },
  { value: "WEEKLY", en: "weekly", fr: "hebdomadaire" },
];

const PAY_METHODS: HrSelectOption[] = [
  { value: "BANK_TRANSFER", en: "by bank transfer", fr: "par virement bancaire" },
  { value: "CHEQUE", en: "by cheque", fr: "par chèque" },
  { value: "CASH", en: "in cash", fr: "en espèces" },
  { value: "MOBILE_MONEY", en: "by mobile money transfer", fr: "par transfert mobile money" },
];

const TRANSPORT: HrSelectOption[] = [
  { value: "AIR", en: "by air", fr: "par voie aérienne" },
  { value: "ROAD", en: "by road", fr: "par voie terrestre" },
  { value: "RAIL", en: "by rail", fr: "par voie ferroviaire" },
  { value: "SEA", en: "by sea", fr: "par voie maritime" },
];

const BORNE_BY: HrSelectOption[] = [
  { value: "FIRM", en: ORGANISATION, fr: ORGANISATION },
  { value: "CLIENT", en: "the client concerned", fr: "le client concerné" },
  { value: "HOST", en: "the host organisation", fr: "l'organisation hôte" },
  { value: "EMPLOYEE", en: "the employee, subject to reimbursement", fr: "l'employé, sous réserve de remboursement" },
];

const INTERNSHIP_KINDS: HrSelectOption[] = [
  { value: "PAID", en: "a paid internship", fr: "un stage rémunéré" },
  { value: "UNPAID", en: "an unpaid academic internship", fr: "un stage académique non rémunéré" },
  { value: "PROFESSIONAL", en: "a professional (pre-qualification) internship", fr: "un stage professionnel" },
];

const INVITATION_COVER: HrSelectOption[] = [
  { value: "HOST", en: ORGANISATION, fr: ORGANISATION },
  { value: "GUEST", en: "the invited party", fr: "la personne invitée" },
  { value: "GUEST_EMPLOYER", en: "the invited party's employer", fr: "l'employeur de la personne invitée" },
  { value: "SHARED", en: `${ORGANISATION} and the invited party jointly`, fr: `${ORGANISATION} et la personne invitée conjointement` },
];

function field(f: Omit<HrDocField, "group"> & { group?: HrDocField["group"] }): HrDocField {
  return { group: "details", ...f };
}

// Subject-of-the-document block, shared by every employee-based attestation.
function subjectFields(opts: { positionRequired?: boolean; startRequired?: boolean; statusRequired?: boolean } = {}): HrDocField[] {
  return [
    field({ key: "employee_title", en: "Courtesy title", fr: "Civilité", kind: "select", required: false, options: HONORIFICS, group: "subject" }),
    field({ key: "employee_full_name", en: "Full name", fr: "Nom et prénoms", kind: "text", required: true, group: "subject", wide: true }),
    field({ key: "employee_position", en: "Position held", fr: "Poste occupé", kind: "text", required: !!opts.positionRequired, group: "subject", translatable: true }),
    field({ key: "employee_department", en: "Department", fr: "Département", kind: "text", required: false, group: "subject", translatable: true }),
    field({ key: "employee_no", en: "Employee number", fr: "Matricule", kind: "text", required: false, group: "subject" }),
    field({ key: "employee_id_type", en: "Identity document", fr: "Pièce d'identité", kind: "select", required: false, options: ID_TYPES, default: "PASSPORT", group: "subject" }),
    field({ key: "employee_id_number", en: "Identity document number", fr: "Numéro de la pièce", kind: "text", required: false, group: "subject" }),
    field({ key: "employee_nationality", en: "Nationality", fr: "Nationalité", kind: "text", required: false, group: "subject", translatable: true }),
    field({ key: "employment_start_date", en: "Employment start date", fr: "Date de prise de service", kind: "date", required: !!opts.startRequired, group: "subject" }),
    field({ key: "employment_status", en: "Contract type", fr: "Type de contrat", kind: "select", required: !!opts.statusRequired, options: EMPLOYMENT_STATUSES, group: "subject" }),
  ];
}

// Issuance + signatory block, shared by every document type.
function commonFields(purposeRequired = true): HrDocField[] {
  return [
    field({ key: "addressee", en: "Addressee (optional)", fr: "Destinataire (facultatif)", kind: "text", required: false, translatable: true, group: "issuance", wide: true }),
    field({ key: "purpose", en: "Purpose of the document", fr: "Objet du document", kind: "textarea", required: purposeRequired, group: "issuance", wide: true, translatable: true }),
    field({ key: "company_address", en: "Office address", fr: "Adresse du cabinet", kind: "text", required: true, default: DEFAULT_ADDRESS, group: "issuance", wide: true }),
    field({ key: "place_of_issue", en: "Place of issue", fr: "Lieu d'établissement", kind: "text", required: true, default: DEFAULT_PLACE, group: "issuance" }),
    field({ key: "issue_date", en: "Date of issue", fr: "Date d'établissement", kind: "date", required: true, group: "issuance" }),
    field({ key: "hr_officer_name", en: "Signatory name", fr: "Nom du signataire", kind: "text", required: true, group: "signatory" }),
    field({ key: "hr_officer_title", en: "Signatory title", fr: "Qualité du signataire", kind: "text", required: true, group: "signatory", translatable: true }),
    field({ key: "hr_phone", en: "HR telephone", fr: "Téléphone RH", kind: "text", required: true, group: "signatory" }),
    field({ key: "hr_email", en: "HR email", fr: "Courriel RH", kind: "text", required: true, group: "signatory" }),
  ];
}

export type HrDocTypeKey =
  | "work_attestation"
  | "employment_confirmation"
  | "leave_attestation"
  | "mission_order"
  | "salary_attestation"
  | "internship_attestation"
  | "invitation_letter"
  | "custom";

export interface HrDocTypeSpec {
  key: HrDocTypeKey;
  /** Segment used in the reference number. */
  code: string;
  en: string;
  fr: string;
  descriptionEn: string;
  descriptionFr: string;
  fields: HrDocField[];
}

export const HR_DOC_TYPES: HrDocTypeSpec[] = [
  {
    key: "work_attestation",
    code: "WA",
    en: "Work Attestation",
    fr: "Attestation de Travail",
    descriptionEn: "Certifies that the person concerned is currently employed by the firm.",
    descriptionFr: "Certifie que la personne concernée est actuellement employée par le cabinet.",
    fields: [
      ...subjectFields({ positionRequired: true, startRequired: true, statusRequired: true }),
      ...commonFields(),
    ],
  },
  {
    key: "employment_confirmation",
    code: "EC",
    en: "Employment Confirmation",
    fr: "Attestation d'Emploi",
    descriptionEn: "Confirms the terms of engagement, including salary and contract particulars.",
    descriptionFr: "Confirme les conditions d'engagement, y compris le salaire et les éléments du contrat.",
    fields: [
      ...subjectFields({ positionRequired: true, startRequired: true, statusRequired: true }),
      field({ key: "contract_end_date", en: "Contract end date (fixed-term only)", fr: "Date de fin de contrat (CDD uniquement)", kind: "date", required: false }),
      field({ key: "gross_monthly_salary", en: "Gross monthly salary", fr: "Salaire mensuel brut", kind: "money", required: false }),
      field({ key: "salary_currency", en: "Currency", fr: "Devise", kind: "select", required: false, options: CURRENCIES, default: "XAF" }),
      field({ key: "cnps_number", en: "CNPS number", fr: "Numéro CNPS", kind: "text", required: false }),
      ...commonFields(),
    ],
  },
  {
    key: "leave_attestation",
    code: "LA",
    en: "Leave Attestation",
    fr: "Attestation de Congé",
    descriptionEn: "Certifies leave granted, its duration and the agreed date of resumption.",
    descriptionFr: "Atteste du congé accordé, de sa durée et de la date de reprise convenue.",
    fields: [
      ...subjectFields({ positionRequired: true, startRequired: true }),
      field({ key: "leave_type", en: "Type of leave", fr: "Nature du congé", kind: "select", required: true, options: LEAVE_TYPES, default: "ANNUAL" }),
      field({ key: "leave_start_date", en: "Leave start date", fr: "Date de début du congé", kind: "date", required: true }),
      field({ key: "leave_end_date", en: "Leave end date", fr: "Date de fin du congé", kind: "date", required: true }),
      field({ key: "resumption_date", en: "Date of resumption", fr: "Date de reprise", kind: "date", required: false }),
      field({ key: "leave_days", en: "Number of working days", fr: "Nombre de jours ouvrables", kind: "text", required: false }),
      field({ key: "destination_country", en: "Country of travel", fr: "Pays de destination", kind: "text", required: false, translatable: true }),
      ...commonFields(),
    ],
  },
  {
    key: "mission_order",
    code: "OM",
    en: "Mission Order",
    fr: "Ordre de Mission",
    descriptionEn: "Instructs an employee to travel on the firm's business and states who bears the cost.",
    descriptionFr: "Ordonne à un employé de se déplacer pour le compte du cabinet et précise la prise en charge des frais.",
    fields: [
      ...subjectFields({ positionRequired: true }),
      field({ key: "mission_destination", en: "Destination (city)", fr: "Destination (ville)", kind: "text", required: true }),
      field({ key: "mission_country", en: "Destination (country)", fr: "Destination (pays)", kind: "text", required: true }),
      field({ key: "mission_start_date", en: "Departure date", fr: "Date de départ", kind: "date", required: true }),
      field({ key: "mission_end_date", en: "Return date", fr: "Date de retour", kind: "date", required: true }),
      field({ key: "mission_purpose", en: "Object of the mission", fr: "Objet de la mission", kind: "textarea", required: true, wide: true, translatable: true }),
      field({ key: "transport_means", en: "Means of transport", fr: "Moyen de transport", kind: "select", required: false, options: TRANSPORT, default: "AIR" }),
      field({ key: "expenses_borne_by", en: "Expenses borne by", fr: "Frais pris en charge par", kind: "select", required: false, options: BORNE_BY, default: "FIRM" }),
      ...commonFields(false),
    ],
  },
  {
    key: "salary_attestation",
    code: "SA",
    en: "Salary Attestation",
    fr: "Attestation de Salaire",
    descriptionEn: "Certifies the remuneration paid to the person concerned.",
    descriptionFr: "Atteste de la rémunération versée à la personne concernée.",
    fields: [
      ...subjectFields({ positionRequired: true, startRequired: true, statusRequired: true }),
      field({ key: "gross_monthly_salary", en: "Gross monthly salary", fr: "Salaire mensuel brut", kind: "money", required: true }),
      field({ key: "net_monthly_salary", en: "Net monthly salary", fr: "Salaire mensuel net", kind: "money", required: false }),
      field({ key: "salary_currency", en: "Currency", fr: "Devise", kind: "select", required: true, options: CURRENCIES, default: "XAF" }),
      field({ key: "pay_frequency", en: "Pay frequency", fr: "Périodicité de paiement", kind: "select", required: false, options: PAY_FREQUENCIES, default: "MONTHLY" }),
      field({ key: "pay_method", en: "Method of payment", fr: "Mode de paiement", kind: "select", required: false, options: PAY_METHODS, default: "BANK_TRANSFER" }),
      field({ key: "bank_name", en: "Bank", fr: "Banque", kind: "text", required: false }),
      field({ key: "cnps_number", en: "CNPS number", fr: "Numéro CNPS", kind: "text", required: false }),
      ...commonFields(),
    ],
  },
  {
    key: "internship_attestation",
    code: "IS",
    en: "Internship Attestation",
    fr: "Attestation de Stage",
    descriptionEn: "Certifies an internship served within the firm and the duties performed.",
    descriptionFr: "Atteste d'un stage effectué au sein du cabinet et des tâches accomplies.",
    fields: [
      field({ key: "employee_title", en: "Courtesy title", fr: "Civilité", kind: "select", required: false, options: HONORIFICS, group: "subject" }),
      field({ key: "employee_full_name", en: "Full name of the intern", fr: "Nom et prénoms du stagiaire", kind: "text", required: true, group: "subject", wide: true }),
      field({ key: "employee_department", en: "Host department", fr: "Département d'accueil", kind: "text", required: true, group: "subject", translatable: true }),
      field({ key: "employee_id_type", en: "Identity document", fr: "Pièce d'identité", kind: "select", required: false, options: ID_TYPES, default: "PASSPORT", group: "subject" }),
      field({ key: "employee_id_number", en: "Identity document number", fr: "Numéro de la pièce", kind: "text", required: false, group: "subject" }),
      field({ key: "employee_nationality", en: "Nationality", fr: "Nationalité", kind: "text", required: false, group: "subject", translatable: true }),
      field({ key: "institution_name", en: "School or university", fr: "Établissement de formation", kind: "text", required: false }),
      field({ key: "internship_kind", en: "Type of internship", fr: "Nature du stage", kind: "select", required: true, options: INTERNSHIP_KINDS, default: "PROFESSIONAL" }),
      field({ key: "internship_start_date", en: "Internship start date", fr: "Date de début du stage", kind: "date", required: true }),
      field({ key: "internship_end_date", en: "Internship end date", fr: "Date de fin du stage", kind: "date", required: true }),
      field({ key: "supervisor_name", en: "Supervisor", fr: "Encadreur", kind: "text", required: false }),
      field({ key: "internship_duties", en: "Duties performed", fr: "Tâches accomplies", kind: "textarea", required: false, wide: true, translatable: true }),
      ...commonFields(),
    ],
  },
  {
    key: "invitation_letter",
    code: "IL",
    en: "Professional Invitation Letter",
    fr: "Lettre d'Invitation Professionnelle",
    descriptionEn: "Invites an external professional to visit the firm and states the cover arrangements.",
    descriptionFr: "Invite un professionnel externe à se rendre au cabinet et précise la prise en charge.",
    fields: [
      field({ key: "guest_title", en: "Courtesy title", fr: "Civilité", kind: "select", required: false, options: HONORIFICS, group: "subject" }),
      field({ key: "guest_full_name", en: "Full name of the guest", fr: "Nom et prénoms de l'invité", kind: "text", required: true, group: "subject", wide: true }),
      field({ key: "guest_position", en: "Position held", fr: "Fonction", kind: "text", required: false, group: "subject", translatable: true }),
      field({ key: "guest_organization", en: "Organisation", fr: "Organisation", kind: "text", required: false, group: "subject" }),
      field({ key: "guest_nationality", en: "Nationality", fr: "Nationalité", kind: "text", required: true, group: "subject", translatable: true }),
      field({ key: "guest_passport_number", en: "Passport number", fr: "Numéro de passeport", kind: "text", required: true, group: "subject" }),
      field({ key: "guest_date_of_birth", en: "Date of birth", fr: "Date de naissance", kind: "date", required: false, group: "subject" }),
      field({ key: "visit_start_date", en: "Start of the visit", fr: "Début du séjour", kind: "date", required: true }),
      field({ key: "visit_end_date", en: "End of the visit", fr: "Fin du séjour", kind: "date", required: true }),
      field({ key: "visit_city", en: "City of the visit", fr: "Ville du séjour", kind: "text", required: true, default: DEFAULT_PLACE }),
      field({ key: "visit_purpose", en: "Object of the visit", fr: "Objet du séjour", kind: "textarea", required: true, wide: true, translatable: true }),
      field({ key: "expenses_borne_by", en: "Expenses borne by", fr: "Frais pris en charge par", kind: "select", required: true, options: INVITATION_COVER, default: "HOST" }),
      field({ key: "accommodation", en: "Accommodation arrangements", fr: "Hébergement prévu", kind: "text", required: false, wide: true, translatable: true }),
      ...commonFields(false),
    ],
  },
  {
    key: "custom",
    code: "HR",
    en: "Other HR Document",
    fr: "Autre Document RH",
    descriptionEn: "Any other HR administrative document, drafted in both languages by the officer.",
    descriptionFr: "Tout autre document administratif RH, rédigé dans les deux langues par le gestionnaire.",
    fields: [
      field({ key: "custom_title_en", en: "Document title (English)", fr: "Titre du document (anglais)", kind: "text", required: true, group: "subject", wide: true }),
      field({ key: "custom_title_fr", en: "Document title (French)", fr: "Titre du document (français)", kind: "text", required: true, group: "subject", wide: true }),
      field({ key: "employee_full_name", en: "Person concerned", fr: "Personne concernée", kind: "text", required: true, group: "subject", wide: true }),
      field({ key: "custom_body_en", en: "Body (English)", fr: "Corps du document (anglais)", kind: "textarea", required: true, wide: true }),
      field({ key: "custom_body_fr", en: "Body (French)", fr: "Corps du document (français)", kind: "textarea", required: true, wide: true }),
      ...commonFields(),
    ],
  },
];

export function docTypeSpec(key: string): HrDocTypeSpec | undefined {
  return HR_DOC_TYPES.find((d) => d.key === key);
}

/** Every input key a document type accepts, including the French companions. */
export function allowedKeys(typeKey: string): string[] {
  const spec = docTypeSpec(typeKey);
  if (!spec) return [];
  const keys: string[] = [];
  for (const f of spec.fields) {
    keys.push(f.key);
    if (f.translatable) keys.push(`${f.key}_fr`);
  }
  return keys;
}

export const HR_DOC_TYPE_KEYS = HR_DOC_TYPES.map((d) => d.key);

// --- Validation ----------------------------------------------------------

export type HrDocInput = Record<string, string>;

export interface MissingField {
  key: string;
  en: string;
  fr: string;
}

export interface ValidationResult {
  ok: boolean;
  missing: MissingField[];
  /** Non-blocking remarks: the document is issuable but weaker without them. */
  advisories: { en: string; fr: string }[];
}

/**
 * Completeness check, run before anything is rendered. Missing required fields
 * are reported back so the officer is asked for them rather than the template
 * silently emitting a blank.
 */
export function validateHrDoc(typeKey: string, input: HrDocInput): ValidationResult {
  const spec = docTypeSpec(typeKey);
  if (!spec) {
    return {
      ok: false,
      missing: [{ key: "document_type", en: "Document type", fr: "Type de document" }],
      advisories: [],
    };
  }

  const missing: MissingField[] = [];
  for (const f of spec.fields) {
    if (!f.required) continue;
    if (!String(input[f.key] ?? "").trim()) missing.push({ key: f.key, en: f.en, fr: f.fr });
  }

  const advisories: ValidationResult["advisories"] = [];
  const idKey = spec.key === "invitation_letter" ? "guest_passport_number" : "employee_id_number";
  if (!String(input[idKey] ?? "").trim()) {
    advisories.push({
      en: "No identity document number was supplied. Consular authorities normally expect the passport number to appear on the document.",
      fr: "Aucun numéro de pièce d'identité n'a été fourni. Les autorités consulaires attendent généralement que le numéro de passeport figure sur le document.",
    });
  }
  if (!String(input.purpose ?? "").trim() && !String(input.visit_purpose ?? "").trim() && !String(input.mission_purpose ?? "").trim()) {
    advisories.push({
      en: "No purpose was stated. A document that does not name its purpose is often rejected at submission.",
      fr: "Aucun objet n'a été indiqué. Un document qui n'énonce pas son objet est souvent rejeté au dépôt.",
    });
  }

  const untranslated = spec.fields.filter(
    (f) => f.translatable && String(input[f.key] ?? "").trim() && !String(input[`${f.key}_fr`] ?? "").trim(),
  );
  if (untranslated.length) {
    advisories.push({
      en: `The French version will reuse the English wording for: ${untranslated.map((f) => f.en).join(", ")}. Supply a French rendering so the French text reads as an original.`,
      fr: `La version française reprendra le libellé anglais pour : ${untranslated.map((f) => f.fr).join(", ")}. Renseignez une formulation française afin que le texte français se lise comme un original.`,
    });
  }

  const start = input.employment_start_date || input.internship_start_date || input.leave_start_date || input.mission_start_date || input.visit_start_date;
  const end = input.internship_end_date || input.leave_end_date || input.mission_end_date || input.visit_end_date;
  if (start && end && isIso(start) && isIso(end) && end < start) {
    missing.push({ key: "date_range", en: "End date must fall on or after the start date", fr: "La date de fin doit être postérieure ou égale à la date de début" });
  }

  return { ok: missing.length === 0, missing, advisories };
}

// --- Reference numbers ---------------------------------------------------

/** DKMN/HR/WA/2026/0001 — stable, quotable, and unique per company and year. */
export function buildReference(code: string, year: number, sequence: number): string {
  return `DKMN/HR/${code}/${year}/${String(sequence).padStart(4, "0")}`;
}

// --- Formatting helpers --------------------------------------------------

const EN_MONTHS = [
  "January", "February", "March", "April", "May", "June",
  "July", "August", "September", "October", "November", "December",
];
const FR_MONTHS = [
  "janvier", "février", "mars", "avril", "mai", "juin",
  "juillet", "août", "septembre", "octobre", "novembre", "décembre",
];

function isIso(value: string): boolean {
  return /^\d{4}-\d{2}-\d{2}/.test(value.trim());
}

/**
 * Render a date as "12 March 2022" / "12 mars 2022". Values already typed in
 * long form by the officer are passed through untouched.
 */
export function formatDocDate(value: string, locale: "en" | "fr"): string {
  const raw = String(value ?? "").trim();
  if (!raw) return "";
  if (!isIso(raw)) return raw;
  const [y, m, d] = raw.slice(0, 10).split("-").map(Number);
  if (!y || !m || !d || m < 1 || m > 12) return raw;
  if (locale === "fr") {
    const day = d === 1 ? "1er" : String(d);
    return `${day} ${FR_MONTHS[m - 1]} ${y}`;
  }
  return `${d} ${EN_MONTHS[m - 1]} ${y}`;
}

export function todayIso(): string {
  return new Date().toISOString().slice(0, 10);
}

const MINOR_UNITS: Record<string, number> = { XAF: 0, XOF: 0, EUR: 2, USD: 2, GBP: 2 };

function groupDigits(intPart: string, sep: string): string {
  return intPart.replace(/\B(?=(\d{3})+(?!\d))/g, sep);
}

/** "1,250,000 XAF" in English, "1 250 000 XAF" in French (non-breaking spaces). */
export function formatAmount(value: string | number, currency: string, locale: "en" | "fr"): string {
  const n = typeof value === "number" ? value : Number(String(value).replace(/[^\d.-]/g, ""));
  if (!isFinite(n)) return String(value);
  const digits = MINOR_UNITS[currency] ?? 2;
  const fixed = Math.abs(n).toFixed(digits);
  const [int, frac] = fixed.split(".");
  const sep = locale === "fr" ? " " : ",";
  const grouped = groupDigits(int, sep);
  const decimal = frac ? (locale === "fr" ? "," : ".") + frac : "";
  const sign = n < 0 ? "-" : "";
  return `${sign}${grouped}${decimal} ${currency}`;
}

const EN_ONES = [
  "zero", "one", "two", "three", "four", "five", "six", "seven", "eight", "nine", "ten",
  "eleven", "twelve", "thirteen", "fourteen", "fifteen", "sixteen", "seventeen", "eighteen", "nineteen",
];
const EN_TENS = ["", "", "twenty", "thirty", "forty", "fifty", "sixty", "seventy", "eighty", "ninety"];

function enUnder1000(n: number): string {
  if (n < 20) return EN_ONES[n];
  if (n < 100) {
    const t = EN_TENS[Math.floor(n / 10)];
    const r = n % 10;
    return r ? `${t}-${EN_ONES[r]}` : t;
  }
  const h = Math.floor(n / 100);
  const r = n % 100;
  // "two hundred and one" — the conjunction is standard in the formal register
  // these documents are read in.
  return r ? `${EN_ONES[h]} hundred and ${enUnder1000(r)}` : `${EN_ONES[h]} hundred`;
}

function enWords(n: number): string {
  if (n === 0) return "zero";
  const scales: [number, string][] = [
    [1_000_000_000, "billion"],
    [1_000_000, "million"],
    [1_000, "thousand"],
  ];
  const parts: string[] = [];
  let rest = Math.floor(n);
  for (const [value, name] of scales) {
    const q = Math.floor(rest / value);
    rest %= value;
    if (q > 0) parts.push(`${enUnder1000(q)} ${name}`);
  }
  if (rest > 0) parts.push(parts.length && rest < 100 ? `and ${enUnder1000(rest)}` : enUnder1000(rest));
  return parts.join(" ");
}

const FR_SMALL = [
  "zéro", "un", "deux", "trois", "quatre", "cinq", "six", "sept", "huit", "neuf", "dix",
  "onze", "douze", "treize", "quatorze", "quinze", "seize",
];
const FR_TENS: Record<number, string> = {
  20: "vingt", 30: "trente", 40: "quarante", 50: "cinquante", 60: "soixante",
};

function frUnder100(n: number): string {
  if (n < 17) return FR_SMALL[n];
  if (n < 20) return `dix-${FR_SMALL[n - 10]}`;
  if (n < 70) {
    const t = Math.floor(n / 10) * 10;
    const r = n % 10;
    if (r === 0) return FR_TENS[t];
    if (r === 1) return `${FR_TENS[t]} et un`;
    return `${FR_TENS[t]}-${FR_SMALL[r]}`;
  }
  if (n < 80) {
    const r = n - 60; // 10..19
    if (r === 11) return "soixante et onze";
    return `soixante-${frUnder100(r)}`;
  }
  const r = n - 80;
  if (r === 0) return "quatre-vingts";
  return `quatre-vingt-${frUnder100(r)}`;
}

function frUnder1000(n: number): string {
  if (n < 100) return frUnder100(n);
  const h = Math.floor(n / 100);
  const r = n % 100;
  const head = h === 1 ? "cent" : `${frUnder100(h)} cent${r === 0 ? "s" : ""}`;
  return r === 0 ? head : `${head} ${frUnder100(r)}`;
}

/**
 * "vingt" and "cent" only take the plural -s when they close the number.
 * Before the invariable "mille" they stay singular ("quatre-vingt mille"),
 * but before the nouns "millions"/"milliards" they keep it ("deux cents
 * millions").
 */
function frInvariable(text: string): string {
  return text.replace(/(vingt|cent)s$/, "$1");
}

function frWords(n: number): string {
  if (n === 0) return "zéro";
  const parts: string[] = [];
  let rest = Math.floor(n);
  const scales: [number, string, string][] = [
    [1_000_000_000, "milliard", "milliards"],
    [1_000_000, "million", "millions"],
  ];
  for (const [value, one, many] of scales) {
    const q = Math.floor(rest / value);
    rest %= value;
    if (q > 0) parts.push(`${frUnder1000(q)} ${q === 1 ? one : many}`);
  }
  const thousands = Math.floor(rest / 1000);
  rest %= 1000;
  if (thousands > 0) parts.push(thousands === 1 ? "mille" : `${frInvariable(frUnder1000(thousands))} mille`);
  if (rest > 0) parts.push(frUnder1000(rest));
  return parts.join(" ");
}

/** True when the number stops on a million or a milliard, which then takes "de". */
function frTakesDe(n: number): boolean {
  const whole = Math.floor(n);
  return whole >= 1_000_000 && whole % 1_000_000 === 0;
}

/** Amount spelled out, as embassies and banks expect on a salary attestation. */
export function amountInWords(value: string | number, currency: string, locale: "en" | "fr"): string {
  const n = typeof value === "number" ? value : Number(String(value).replace(/[^\d.-]/g, ""));
  if (!isFinite(n)) return "";
  const digits = MINOR_UNITS[currency] ?? 2;
  const whole = Math.floor(Math.abs(n));
  const cents = Math.round((Math.abs(n) - whole) * 10 ** digits);
  const one = whole === 1;
  const unitEn: Record<string, string> = one
    ? { XAF: "CFA franc", XOF: "CFA franc", EUR: "euro", USD: "US dollar", GBP: "pound sterling" }
    : { XAF: "CFA francs", XOF: "CFA francs", EUR: "euros", USD: "US dollars", GBP: "pounds sterling" };
  const unitFr: Record<string, string> = one
    ? { XAF: "franc CFA", XOF: "franc CFA", EUR: "euro", USD: "dollar américain", GBP: "livre sterling" }
    : { XAF: "francs CFA", XOF: "francs CFA", EUR: "euros", USD: "dollars américains", GBP: "livres sterling" };
  if (locale === "fr") {
    const de = frTakesDe(whole) ? "de " : "";
    const head = `${frWords(whole)} ${de}${unitFr[currency] ?? currency}`;
    return cents > 0 ? `${head} et ${cents}/${10 ** digits}` : head;
  }
  const head = `${enWords(whole)} ${unitEn[currency] ?? currency}`;
  return cents > 0 ? `${head} and ${cents}/${10 ** digits}` : head;
}

function optionLabel(options: HrSelectOption[], value: string, locale: "en" | "fr"): string {
  const found = options.find((o) => o.value === value);
  if (found) return locale === "fr" ? found.fr : found.en;
  return value;
}

/** Whole days between two ISO dates, inclusive of both ends. */
function inclusiveDays(from: string, to: string): number | null {
  if (!isIso(from) || !isIso(to)) return null;
  const a = Date.parse(`${from.slice(0, 10)}T00:00:00Z`);
  const b = Date.parse(`${to.slice(0, 10)}T00:00:00Z`);
  if (!isFinite(a) || !isFinite(b) || b < a) return null;
  return Math.round((b - a) / 86_400_000) + 1;
}

// --- Rendering -----------------------------------------------------------

export interface RenderedHrDoc {
  /** Bilingual title, used as the document heading and the file name. */
  title: string;
  subtitle: string;
  /** Markdown understood by lib/docgen (headings, paragraphs, bullets, page breaks). */
  markdown: string;
  /** Footer line repeated on every page. */
  footer: string;
  reference: string;
}

export const PAGE_BREAK = "[[PAGEBREAK]]";

interface Version {
  /** Uppercased document title for this language. */
  heading: string;
  salutation: string;
  /** Certification paragraphs, in order. */
  body: string[];
  purpose: string;
  closing: string;
}

function ctx(input: HrDocInput, locale?: "en" | "fr") {
  const v = (key: string) => String(input[key] ?? "").trim();
  const has = (key: string) => v(key).length > 0;
  // Translatable free text: use the French rendering the officer supplied,
  // falling back to the English one so a version is never left with a hole.
  const tv = (key: string) => (locale === "fr" ? v(`${key}_fr`) || v(key) : v(key));
  return { v, has, tv };
}

/** "Mr John Doe" / "M. John Doe" — the honorific is only used when supplied. */
function personName(input: HrDocInput, locale: "en" | "fr", titleKey = "employee_title", nameKey = "employee_full_name"): string {
  const { v } = ctx(input);
  const name = v(nameKey);
  const title = v(titleKey);
  if (!title) return name;
  return `${optionLabel(HONORIFICS, title, locale)} ${name}`.trim();
}

/** ", holder of passport No. PA1234567," — omitted entirely when unknown. */
function identityClause(input: HrDocInput, locale: "en" | "fr", typeKey = "employee_id_type", numberKey = "employee_id_number"): string {
  const { v, has } = ctx(input);
  if (!has(numberKey)) return "";
  const kind = optionLabel(ID_TYPES, v(typeKey) || "PASSPORT", locale);
  return locale === "fr"
    ? `, titulaire du ${kind} n° ${v(numberKey)}`
    : `, holder of ${kind} No. ${v(numberKey)}`;
}

/** French elision: "en qualité d'Assistant" rather than "de Assistant". */
function frDe(word: string): string {
  return /^[aeiouyàâäéèêëîïôöûüh]/i.test(word.trim()) ? `d'${word}` : `de ${word}`;
}

function positionClause(input: HrDocInput, locale: "en" | "fr"): string {
  const { has, tv } = ctx(input, locale);
  if (!has("employee_position")) return "";
  const dept = has("employee_department")
    ? locale === "fr"
      ? ` au sein du département ${tv("employee_department")}`
      : ` within the ${tv("employee_department")} Department`
    : "";
  return locale === "fr"
    ? ` en qualité ${frDe(tv("employee_position"))}${dept}`
    : ` in the capacity of ${tv("employee_position")}${dept}`;
}

function buildVersion(typeKey: HrDocTypeKey, input: HrDocInput, locale: "en" | "fr"): Version {
  const { v, has, tv } = ctx(input, locale);
  const fr = locale === "fr";
  const d = (key: string) => formatDocDate(v(key), locale);
  const spec = docTypeSpec(typeKey)!;
  const subject = personName(input, locale);
  const identity = identityClause(input, locale);
  const purposeText = tv("purpose");

  const heading = (fr ? spec.fr : spec.en).toUpperCase();
  const salutation = has("addressee")
    ? tv("addressee")
    : fr
      ? "À QUI DE DROIT"
      : "TO WHOM IT MAY CONCERN";

  const undersigned = fr
    ? `Je soussigné(e), ${v("hr_officer_name")}, ${tv("hr_officer_title")} de ${ORGANISATION}, certifie par la présente que :`
    : `The undersigned, ${v("hr_officer_name")}, ${tv("hr_officer_title")} of ${ORGANISATION}, hereby certifies that:`;

  const body: string[] = [];
  let purpose: string;
  let closing: string;

  switch (typeKey) {
    case "work_attestation": {
      body.push(undersigned);
      const status = has("employment_status") ? optionLabel(EMPLOYMENT_STATUSES, v("employment_status"), locale) : "";
      body.push(
        fr
          ? `${subject}${identity}, est employé(e) par ${ORGANISATION} depuis le ${d("employment_start_date")}${positionClause(input, locale)}, sous ${status}.`
          : `${subject}${identity}, has been employed by ${ORGANISATION} since ${d("employment_start_date")}${positionClause(input, locale)}, under ${status}.`,
      );
      if (has("employee_no")) {
        body.push(fr ? `Matricule interne : ${v("employee_no")}.` : `Internal employee number: ${v("employee_no")}.`);
      }
      body.push(
        fr
          ? `À la date d'établissement de la présente attestation, le contrat de travail de l'intéressé(e) est en cours d'exécution et n'a fait l'objet d'aucune rupture ni d'aucun préavis.`
          : `As at the date of this attestation, the employment relationship of the person concerned is current and has been neither terminated nor placed under notice.`,
      );
      body.push(
        fr
          ? `L'intéressé(e) s'acquitte de ses fonctions à la satisfaction du cabinet et demeure lié(e) à ${ORGANISATION} par les obligations professionnelles attachées à son poste.`
          : `The person concerned discharges their duties to the satisfaction of the firm and remains bound to ${ORGANISATION} by the professional obligations attaching to the post.`,
      );
      purpose = fr
        ? `La présente attestation est délivrée à l'intéressé(e), sur sa demande, pour servir et valoir ce que de droit, et plus particulièrement aux fins de : ${purposeText}.`
        : `This attestation is issued to the person concerned, at their request, to serve and avail as of right, and more particularly for the following purpose: ${purposeText}.`;
      closing = fr
        ? `${ORGANISATION} atteste de l'exactitude des mentions qui précèdent et se tient à la disposition de toute autorité compétente pour toute vérification utile.`
        : `${ORGANISATION} certifies the accuracy of the particulars set out above and remains at the disposal of any competent authority for any verification required.`;
      break;
    }

    case "employment_confirmation": {
      body.push(undersigned);
      const status = has("employment_status") ? optionLabel(EMPLOYMENT_STATUSES, v("employment_status"), locale) : "";
      body.push(
        fr
          ? `${subject}${identity}, est lié(e) à ${ORGANISATION} par ${status}, ayant pris effet le ${d("employment_start_date")}${positionClause(input, locale)}.`
          : `${subject}${identity}, is engaged by ${ORGANISATION} under ${status}, which took effect on ${d("employment_start_date")}${positionClause(input, locale)}.`,
      );
      if (has("contract_end_date")) {
        body.push(
          fr
            ? `Le contrat est conclu jusqu'au ${d("contract_end_date")}.`
            : `The contract runs until ${d("contract_end_date")}.`,
        );
      }
      if (has("gross_monthly_salary")) {
        const cur = v("salary_currency") || "XAF";
        body.push(
          fr
            ? `La rémunération mensuelle brute de l'intéressé(e) s'élève à ${formatAmount(v("gross_monthly_salary"), cur, "fr")} (${amountInWords(v("gross_monthly_salary"), cur, "fr")}).`
            : `The gross monthly remuneration of the person concerned amounts to ${formatAmount(v("gross_monthly_salary"), cur, "en")} (${amountInWords(v("gross_monthly_salary"), cur, "en")}).`,
        );
      }
      if (has("cnps_number")) {
        body.push(
          fr
            ? `L'intéressé(e) est régulièrement déclaré(e) à la Caisse Nationale de Prévoyance Sociale sous le numéro ${v("cnps_number")}.`
            : `The person concerned is duly registered with the National Social Insurance Fund (CNPS) under number ${v("cnps_number")}.`,
        );
      }
      body.push(
        fr
          ? `Le contrat est en cours d'exécution à la date de la présente et n'a fait l'objet d'aucune rupture ni d'aucun préavis.`
          : `The contract is current as at the date hereof and has been neither terminated nor placed under notice.`,
      );
      purpose = fr
        ? `La présente attestation d'emploi est délivrée à l'intéressé(e), sur sa demande, aux fins de : ${purposeText}.`
        : `This employment confirmation is issued to the person concerned, at their request, for the following purpose: ${purposeText}.`;
      closing = fr
        ? `${ORGANISATION} confirme l'exactitude des informations ci-dessus et se tient à la disposition de toute autorité compétente pour toute vérification utile.`
        : `${ORGANISATION} confirms the accuracy of the information set out above and remains at the disposal of any competent authority for any verification required.`;
      break;
    }

    case "leave_attestation": {
      body.push(undersigned);
      body.push(
        fr
          ? `${subject}${identity}, est employé(e) par ${ORGANISATION} depuis le ${d("employment_start_date")}${positionClause(input, locale)}.`
          : `${subject}${identity}, has been employed by ${ORGANISATION} since ${d("employment_start_date")}${positionClause(input, locale)}.`,
      );
      const days = v("leave_days") || (inclusiveDays(v("leave_start_date"), v("leave_end_date")) ?? "");
      const leaveKind = optionLabel(LEAVE_TYPES, v("leave_type") || "ANNUAL", locale);
      body.push(
        fr
          ? `${ORGANISATION} lui a accordé un ${leaveKind} du ${d("leave_start_date")} au ${d("leave_end_date")} inclus${days ? `, soit ${days} jour(s)` : ""}.`
          : `${ORGANISATION} has granted the person concerned ${leaveKind} from ${d("leave_start_date")} to ${d("leave_end_date")} inclusive${days ? `, being ${days} day(s)` : ""}.`,
      );
      if (has("resumption_date")) {
        body.push(
          fr
            ? `L'intéressé(e) est attendu(e) à son poste le ${d("resumption_date")}, date de reprise effective de ses fonctions.`
            : `The person concerned is expected back at their post on ${d("resumption_date")}, being the agreed date of resumption of duties.`,
        );
      }
      if (has("destination_country")) {
        body.push(
          fr
            ? `Durant cette période, l'intéressé(e) a déclaré séjourner en ${tv("destination_country")}.`
            : `During that period, the person concerned has declared that they will be staying in ${tv("destination_country")}.`,
        );
      }
      body.push(
        fr
          ? `Le poste de l'intéressé(e) est maintenu pendant toute la durée du congé et son contrat de travail se poursuit à l'issue de celui-ci.`
          : `The post of the person concerned is maintained throughout the period of leave and their contract of employment continues thereafter.`,
      );
      purpose = fr
        ? `La présente attestation de congé est délivrée à l'intéressé(e), sur sa demande, aux fins de : ${purposeText}.`
        : `This leave attestation is issued to the person concerned, at their request, for the following purpose: ${purposeText}.`;
      closing = fr
        ? `${ORGANISATION} atteste de l'exactitude des mentions qui précèdent et se tient à la disposition de toute autorité compétente pour toute vérification utile.`
        : `${ORGANISATION} certifies the accuracy of the particulars set out above and remains at the disposal of any competent authority for any verification required.`;
      break;
    }

    case "mission_order": {
      body.push(
        fr
          ? `Je soussigné(e), ${v("hr_officer_name")}, ${tv("hr_officer_title")} de ${ORGANISATION}, donne par le présent ordre de mission à :`
          : `The undersigned, ${v("hr_officer_name")}, ${tv("hr_officer_title")} of ${ORGANISATION}, hereby issues the following mission order to:`,
      );
      body.push(
        fr
          ? `${subject}${identity}${positionClause(input, locale)}${has("employee_no") ? `, matricule ${v("employee_no")}` : ""}.`
          : `${subject}${identity}${positionClause(input, locale)}${has("employee_no") ? `, employee number ${v("employee_no")}` : ""}.`,
      );
      const nights = inclusiveDays(v("mission_start_date"), v("mission_end_date"));
      body.push(
        fr
          ? `L'intéressé(e) est chargé(e) de se rendre à ${v("mission_destination")} (${v("mission_country")}) du ${d("mission_start_date")} au ${d("mission_end_date")} inclus${nights ? `, soit ${nights} jour(s)` : ""}${has("transport_means") ? `, ${optionLabel(TRANSPORT, v("transport_means"), locale)}` : ""}.`
          : `The person concerned is instructed to travel to ${v("mission_destination")} (${v("mission_country")}) from ${d("mission_start_date")} to ${d("mission_end_date")} inclusive${nights ? `, being ${nights} day(s)` : ""}${has("transport_means") ? `, ${optionLabel(TRANSPORT, v("transport_means"), locale)}` : ""}.`,
      );
      body.push(
        fr
          ? `Objet de la mission : ${tv("mission_purpose")}.`
          : `Object of the mission: ${tv("mission_purpose")}.`,
      );
      body.push(
        fr
          ? `Les frais de transport, d'hébergement et de séjour afférents à cette mission sont pris en charge par ${optionLabel(BORNE_BY, v("expenses_borne_by") || "FIRM", locale)}.`
          : `The transport, accommodation and subsistence costs of this mission are borne by ${optionLabel(BORNE_BY, v("expenses_borne_by") || "FIRM", locale)}.`,
      );
      body.push(
        fr
          ? `L'intéressé(e) demeure salarié(e) de ${ORGANISATION} pendant toute la durée de la mission et est tenu(e) de regagner son poste à l'issue de celle-ci.`
          : `The person concerned remains an employee of ${ORGANISATION} for the whole duration of the mission and is required to resume their post at its conclusion.`,
      );
      purpose = fr
        ? `Le présent ordre de mission est établi pour servir et valoir ce que de droit, notamment auprès des autorités consulaires, frontalières et douanières appelées à en connaître${purposeText ? `, et plus particulièrement aux fins de : ${purposeText}` : ""}.`
        : `This mission order is issued to serve and avail as of right, in particular before the consular, border and customs authorities called upon to consider it${purposeText ? `, and more particularly for the following purpose: ${purposeText}` : ""}.`;
      closing = fr
        ? `${ORGANISATION} prie les autorités compétentes de bien vouloir faciliter à l'intéressé(e) l'accomplissement de la mission ci-dessus définie.`
        : `${ORGANISATION} respectfully requests the competent authorities to afford the person concerned every facility in the accomplishment of the mission defined above.`;
      break;
    }

    case "salary_attestation": {
      const cur = v("salary_currency") || "XAF";
      body.push(undersigned);
      const status = has("employment_status") ? optionLabel(EMPLOYMENT_STATUSES, v("employment_status"), locale) : "";
      body.push(
        fr
          ? `${subject}${identity}, est employé(e) par ${ORGANISATION} depuis le ${d("employment_start_date")}${positionClause(input, locale)}, sous ${status}.`
          : `${subject}${identity}, has been employed by ${ORGANISATION} since ${d("employment_start_date")}${positionClause(input, locale)}, under ${status}.`,
      );
      body.push(
        fr
          ? `La rémunération mensuelle brute de l'intéressé(e) s'élève à ${formatAmount(v("gross_monthly_salary"), cur, "fr")} (${amountInWords(v("gross_monthly_salary"), cur, "fr")}).`
          : `The gross monthly remuneration of the person concerned amounts to ${formatAmount(v("gross_monthly_salary"), cur, "en")} (${amountInWords(v("gross_monthly_salary"), cur, "en")}).`,
      );
      if (has("net_monthly_salary")) {
        body.push(
          fr
            ? `La rémunération mensuelle nette, après déduction des cotisations sociales et de l'impôt sur le revenu, s'élève à ${formatAmount(v("net_monthly_salary"), cur, "fr")} (${amountInWords(v("net_monthly_salary"), cur, "fr")}).`
            : `The net monthly remuneration, after deduction of social security contributions and income tax, amounts to ${formatAmount(v("net_monthly_salary"), cur, "en")} (${amountInWords(v("net_monthly_salary"), cur, "en")}).`,
        );
      }
      const freq = optionLabel(PAY_FREQUENCIES, v("pay_frequency") || "MONTHLY", locale);
      const method = optionLabel(PAY_METHODS, v("pay_method") || "BANK_TRANSFER", locale);
      body.push(
        fr
          ? `Cette rémunération est versée sur une base ${freq}, ${method}${has("bank_name") ? ` auprès de ${v("bank_name")}` : ""}.`
          : `This remuneration is paid on a ${freq} basis, ${method}${has("bank_name") ? ` through ${v("bank_name")}` : ""}.`,
      );
      if (has("cnps_number")) {
        body.push(
          fr
            ? `L'intéressé(e) est régulièrement déclaré(e) à la Caisse Nationale de Prévoyance Sociale sous le numéro ${v("cnps_number")}.`
            : `The person concerned is duly registered with the National Social Insurance Fund (CNPS) under number ${v("cnps_number")}.`,
        );
      }
      purpose = fr
        ? `La présente attestation de salaire est délivrée à l'intéressé(e), sur sa demande, aux fins de : ${purposeText}.`
        : `This salary attestation is issued to the person concerned, at their request, for the following purpose: ${purposeText}.`;
      closing = fr
        ? `${ORGANISATION} atteste de l'exactitude des montants indiqués, tels qu'ils ressortent de ses livres de paie, et se tient à la disposition de toute autorité compétente pour toute vérification utile.`
        : `${ORGANISATION} certifies the accuracy of the amounts stated, as they appear in its payroll records, and remains at the disposal of any competent authority for any verification required.`;
      break;
    }

    case "internship_attestation": {
      body.push(undersigned);
      const kind = optionLabel(INTERNSHIP_KINDS, v("internship_kind") || "PROFESSIONAL", locale);
      const days = inclusiveDays(v("internship_start_date"), v("internship_end_date"));
      body.push(
        fr
          ? `${subject}${identity}, a effectué ${kind} au sein de ${ORGANISATION}, département ${tv("employee_department")}, du ${d("internship_start_date")} au ${d("internship_end_date")} inclus${days ? `, soit ${days} jour(s)` : ""}.`
          : `${subject}${identity}, served ${kind} within ${ORGANISATION}, ${tv("employee_department")} Department, from ${d("internship_start_date")} to ${d("internship_end_date")} inclusive${days ? `, being ${days} day(s)` : ""}.`,
      );
      if (has("institution_name")) {
        body.push(
          fr
            ? `Ce stage s'inscrivait dans le cadre de la formation suivie par l'intéressé(e) à ${v("institution_name")}.`
            : `The internship formed part of the course of study followed by the person concerned at ${v("institution_name")}.`,
        );
      }
      if (has("internship_duties")) {
        body.push(
          fr
            ? `Au cours de ce stage, l'intéressé(e) a été chargé(e) des tâches suivantes : ${tv("internship_duties")}.`
            : `In the course of the internship, the person concerned was entrusted with the following duties: ${tv("internship_duties")}.`,
        );
      }
      if (has("supervisor_name")) {
        body.push(
          fr
            ? `Le stage s'est déroulé sous l'encadrement de ${v("supervisor_name")}.`
            : `The internship was carried out under the supervision of ${v("supervisor_name")}.`,
        );
      }
      body.push(
        fr
          ? `L'intéressé(e) a accompli ses obligations de stage avec assiduité et a fait preuve d'un comportement professionnel satisfaisant.`
          : `The person concerned fulfilled the obligations of the internship with diligence and displayed satisfactory professional conduct.`,
      );
      purpose = fr
        ? `La présente attestation de stage est délivrée à l'intéressé(e), sur sa demande, aux fins de : ${purposeText}.`
        : `This internship attestation is issued to the person concerned, at their request, for the following purpose: ${purposeText}.`;
      closing = fr
        ? `${ORGANISATION} atteste de l'exactitude des mentions qui précèdent et se tient à la disposition de toute autorité compétente pour toute vérification utile.`
        : `${ORGANISATION} certifies the accuracy of the particulars set out above and remains at the disposal of any competent authority for any verification required.`;
      break;
    }

    case "invitation_letter": {
      const guest = personName(input, locale, "guest_title", "guest_full_name");
      const org = has("guest_organization")
        ? fr
          ? `, ${tv("guest_position") ? `${tv("guest_position")} au sein de ` : ""}${v("guest_organization")}`
          : `, ${tv("guest_position") ? `${tv("guest_position")} at ` : ""}${v("guest_organization")}`
        : "";
      body.push(
        fr
          ? `${ORGANISATION}, cabinet d'avocats établi à l'adresse indiquée en en-tête, a l'honneur d'inviter officiellement :`
          : `${ORGANISATION}, a law firm established at the address shown above, has the honour formally to invite:`,
      );
      body.push(
        fr
          ? `${guest}${org}, de nationalité ${tv("guest_nationality")}, titulaire du passeport n° ${v("guest_passport_number")}${has("guest_date_of_birth") ? `, né(e) le ${d("guest_date_of_birth")}` : ""}.`
          : `${guest}${org}, a national of ${tv("guest_nationality")}, holder of passport No. ${v("guest_passport_number")}${has("guest_date_of_birth") ? `, born on ${d("guest_date_of_birth")}` : ""}.`,
      );
      const days = inclusiveDays(v("visit_start_date"), v("visit_end_date"));
      body.push(
        fr
          ? `La personne invitée est attendue à ${v("visit_city")} du ${d("visit_start_date")} au ${d("visit_end_date")} inclus${days ? `, soit ${days} jour(s)` : ""}.`
          : `The invited party is expected in ${v("visit_city")} from ${d("visit_start_date")} to ${d("visit_end_date")} inclusive${days ? `, being ${days} day(s)` : ""}.`,
      );
      body.push(
        fr
          ? `Objet du séjour : ${tv("visit_purpose")}.`
          : `Object of the visit: ${tv("visit_purpose")}.`,
      );
      body.push(
        fr
          ? `Les frais de voyage, d'hébergement et de séjour afférents à cette visite sont pris en charge par ${optionLabel(INVITATION_COVER, v("expenses_borne_by") || "HOST", locale)}.${has("accommodation") ? ` Hébergement prévu : ${tv("accommodation")}.` : ""}`
          : `The travel, accommodation and subsistence costs of this visit are borne by ${optionLabel(INVITATION_COVER, v("expenses_borne_by") || "HOST", locale)}.${has("accommodation") ? ` Accommodation arrangements: ${tv("accommodation")}.` : ""}`,
      );
      body.push(
        fr
          ? `${ORGANISATION} se porte garant du caractère strictement professionnel de ce séjour et confirme que la personne invitée quittera le territoire à l'expiration de la période indiquée ci-dessus.`
          : `${ORGANISATION} vouches for the strictly professional character of this visit and confirms that the invited party will leave the territory upon expiry of the period stated above.`,
      );
      purpose = fr
        ? `La présente lettre d'invitation est établie à l'attention des autorités consulaires et migratoires compétentes, à l'appui de la demande de visa de la personne invitée${purposeText ? `, et plus particulièrement aux fins de : ${purposeText}` : ""}.`
        : `This letter of invitation is issued for the attention of the competent consular and immigration authorities, in support of the invited party's visa application${purposeText ? `, and more particularly for the following purpose: ${purposeText}` : ""}.`;
      closing = fr
        ? `${ORGANISATION} prie les autorités compétentes de bien vouloir réserver une suite favorable à cette demande et se tient à leur entière disposition pour toute information complémentaire.`
        : `${ORGANISATION} respectfully requests the competent authorities to give this application their favourable consideration and remains entirely at their disposal for any further information.`;
      break;
    }

    case "custom":
    default: {
      body.push(undersigned);
      const text = fr ? v("custom_body_fr") : v("custom_body_en");
      for (const para of text.split(/\n{2,}|\n/).map((p) => p.trim()).filter(Boolean)) {
        body.push(para);
      }
      purpose = fr
        ? `Le présent document est délivré à ${subject}, sur sa demande, aux fins de : ${purposeText}.`
        : `This document is issued to ${subject}, at their request, for the following purpose: ${purposeText}.`;
      closing = fr
        ? `${ORGANISATION} atteste de l'exactitude des mentions qui précèdent et se tient à la disposition de toute autorité compétente pour toute vérification utile.`
        : `${ORGANISATION} certifies the accuracy of the particulars set out above and remains at the disposal of any competent authority for any verification required.`;
      break;
    }
  }

  return { heading, salutation, body, purpose, closing };
}

function versionMarkdown(
  typeKey: HrDocTypeKey,
  input: HrDocInput,
  locale: "en" | "fr",
  reference: string,
): string[] {
  const { v, has, tv } = ctx(input, locale);
  const fr = locale === "fr";
  const version = buildVersion(typeKey, input, locale);
  const lines: string[] = [];

  // Letterhead.
  lines.push(`## ${ORGANISATION.toUpperCase()}`);
  lines.push(
    fr && v("company_address") === DEFAULT_ADDRESS ? DEFAULT_ADDRESS_FR : v("company_address"),
  );
  lines.push(
    fr
      ? `Téléphone : ${v("hr_phone")} — Courriel : ${v("hr_email")}`
      : `Telephone: ${v("hr_phone")} — Email: ${v("hr_email")}`,
  );
  lines.push("");
  lines.push(fr ? "### VERSION FRANÇAISE" : "### ENGLISH VERSION");
  lines.push("");
  lines.push(fr ? `Référence : ${reference}` : `Reference: ${reference}`);
  lines.push(
    fr
      ? `${v("place_of_issue")}, le ${formatDocDate(v("issue_date"), "fr")}`
      : `${v("place_of_issue")}, ${formatDocDate(v("issue_date"), "en")}`,
  );
  lines.push("");

  // Title of the instrument, then the addressee.
  lines.push(`## ${version.heading}`);
  lines.push("");
  lines.push(`**${version.salutation}**`);
  lines.push("");

  for (const para of version.body) {
    lines.push(para);
    lines.push("");
  }

  lines.push(fr ? "### OBJET" : "### PURPOSE");
  lines.push(version.purpose);
  lines.push("");
  lines.push(fr ? "### CONFIRMATION" : "### CONFIRMATION");
  lines.push(version.closing);
  lines.push("");

  lines.push(fr ? `Fait à ${v("place_of_issue")}, le ${formatDocDate(v("issue_date"), "fr")}.` : `Done at ${v("place_of_issue")}, on ${formatDocDate(v("issue_date"), "en")}.`);
  lines.push("");

  // Signature block.
  lines.push(fr ? "### SIGNATURE" : "### SIGNATURE");
  lines.push(fr ? `Pour et au nom de ${ORGANISATION}` : `For and on behalf of ${ORGANISATION}`);
  lines.push("");
  lines.push("_______________________________________");
  lines.push(`**${v("hr_officer_name")}**`);
  lines.push(tv("hr_officer_title"));
  lines.push(
    fr
      ? `Téléphone : ${v("hr_phone")} — Courriel : ${v("hr_email")}`
      : `Telephone: ${v("hr_phone")} — Email: ${v("hr_email")}`,
  );
  lines.push(fr ? "(Signature et cachet du cabinet)" : "(Signature and company stamp)");
  lines.push("");

  // Verification instructions, restated in full inside each version.
  lines.push(fr ? "### VÉRIFICATION" : "### VERIFICATION");
  lines.push(
    fr
      ? `Le présent document est enregistré sous la référence ${reference} dans le registre des documents du personnel de ${ORGANISATION}. Toute autorité destinataire peut en vérifier l'authenticité en écrivant à ${v("hr_email")} ou en appelant le ${v("hr_phone")}, en rappelant la référence ci-dessus. Le document n'est valable que revêtu de la signature et du cachet du cabinet.`
      : `This document is recorded under reference ${reference} in the personnel document register of ${ORGANISATION}. Any receiving authority may verify its authenticity by writing to ${v("hr_email")} or by telephoning ${v("hr_phone")}, quoting the reference above. The document is valid only when bearing the signature and stamp of the firm.`,
  );
  if (has("addressee")) {
    lines.push(
      fr
        ? `Document établi à l'attention de : ${tv("addressee")}.`
        : `Document issued for the attention of: ${tv("addressee")}.`,
    );
  }

  return lines;
}

/**
 * Render the complete bilingual instrument: English first, French second, each
 * on its own page and each self-contained (letterhead, reference, body,
 * purpose, signature, verification) so either version can be presented alone.
 */
export function renderHrDocument(typeKey: string, input: HrDocInput, reference: string): RenderedHrDoc {
  const spec = docTypeSpec(typeKey);
  if (!spec) throw new Error("unknown_document_type");
  const key = spec.key;
  const { v } = ctx(input);

  const titleEn = key === "custom" ? v("custom_title_en") : spec.en;
  const titleFr = key === "custom" ? v("custom_title_fr") : spec.fr;

  const lines = [
    ...versionMarkdown(key, input, "en", reference),
    "",
    PAGE_BREAK,
    "",
    ...versionMarkdown(key, input, "fr", reference),
  ];

  const issued = formatDocDate(v("issue_date") || todayIso(), "en");
  return {
    title: `${titleEn.toUpperCase()} / ${titleFr.toUpperCase()}`,
    subtitle: `${ORGANISATION} — ${reference} — ${issued}`,
    markdown: lines.join("\n"),
    footer:
      `${reference} — ${ORGANISATION}. Verify with Human Resources at ${v("hr_email")} / ${v("hr_phone")}, quoting this reference. ` +
      `Vérification auprès des Ressources Humaines à ${v("hr_email")} / ${v("hr_phone")}, en rappelant cette référence.`,
    reference,
  };
}

/** File-name stem for the exported PDF/DOCX. */
export function documentFileStem(typeKey: string, input: HrDocInput, reference: string): string {
  const spec = docTypeSpec(typeKey);
  const who = String(input.employee_full_name || input.guest_full_name || "").trim();
  const parts = [spec?.en ?? "HR Document", who, reference.replace(/\//g, "-")].filter(Boolean);
  return parts
    .join(" - ")
    .replace(/[^a-zA-Z0-9 _-]/g, "")
    .trim()
    .replace(/\s+/g, "_")
    .slice(0, 90) || "HR_Document";
}
