import { NextRequest } from "next/server";
import { handle } from "@/lib/api";
import { prisma } from "@/lib/prisma";
import { requirePermission, AuthError } from "@/lib/auth";
import { kycScreen } from "@/lib/ai";
import { resolveAiConfig } from "@/lib/settings";
import { writeAudit } from "@/lib/audit";

export const dynamic = "force-dynamic";

// POST /api/clients/:id/kyc-verify
// Runs KYC due diligence and files the report on the client:
//  - With an AI key configured: Claude web-search screening across the public
//    internet (sanctions/PEP, adverse media, registrations) with a risk rating.
//  - Without: an internal-data report (profile, history) marked as such.
// Outcome: LOW/MEDIUM risk -> kycStatus VERIFIED (amlRisk updated);
//          HIGH risk       -> stays PENDING + amlRisk HIGH for partner review.
export async function POST(_req: NextRequest, { params }: { params: { id: string } }) {
  return handle(async () => {
    const user = await requirePermission("client:manage");
    const client = await prisma.client.findFirst({
      where: { id: params.id, companyId: user.companyId, deletedAt: null },
      include: {
        matters: { select: { code: true, status: true } },
        conflictChecks: { orderBy: { createdAt: "desc" }, take: 1 },
      },
    });
    if (!client) throw new AuthError(404, "not_found");

    const cfg = await resolveAiConfig(user.companyId);
    let screening: string;
    let riskLevel: "LOW" | "MEDIUM" | "HIGH";
    let source: "internet" | "internal";

    if (cfg.apiKey) {
      try {
        const r = await kycScreen(
          { name: client.name, type: client.type, taxId: client.taxId, email: client.email, country: "Cameroon" },
          cfg,
        );
        screening = r.report;
        riskLevel = r.riskLevel;
        source = "internet";
      } catch {
        // Provider outage should not block onboarding — fall back, flag for review.
        screening = "_Automated internet screening failed (provider error). Manual screening required._";
        riskLevel = "MEDIUM";
        source = "internal";
      }
    } else {
      screening =
        "_Automated internet screening unavailable — no AI key configured. " +
        "This report is based on internal records only; complete manual screening " +
        "(sanctions lists, registry extracts) before onboarding high-value clients._";
      riskLevel = client.amlRisk === "HIGH" ? "HIGH" : "LOW";
      source = "internal";
    }

    const lastConflict = client.conflictChecks[0];
    const report = [
      `# KYC Verification Report`,
      ``,
      `**Client:** ${client.name} (${client.type})`,
      `**Tax ID:** ${client.taxId ?? "—"}   **Email:** ${client.email ?? "—"}`,
      `**Verified by:** ${user.fullName}   **Date:** ${new Date().toISOString().slice(0, 10)}`,
      `**Screening source:** ${source === "internet" ? "Internet screening (AI-assisted web search)" : "Internal records only"}`,
      `**Risk assessment:** ${riskLevel}`,
      ``,
      `## Internal profile`,
      `- Declared AML risk at onboarding: ${client.amlRisk}`,
      `- Conflict status: ${client.conflictStatus}` +
        (lastConflict ? ` (last check ${lastConflict.createdAt.toISOString().slice(0, 10)})` : ""),
      `- Matters on file: ${client.matters.length}` +
        (client.matters.length ? ` (${client.matters.map((m) => m.code).join(", ")})` : ""),
      ``,
      `## Screening findings`,
      screening,
      ``,
      `---`,
      `Generated by Dentons KMN Finance. AI-assisted screening supports but does not ` +
        `replace the firm's regulatory KYC obligations; retain identity documents in the client file.`,
    ].join("\n");

    const verified = riskLevel !== "HIGH";
    const [doc] = await prisma.$transaction([
      prisma.clientDocument.create({
        data: {
          companyId: user.companyId,
          clientId: client.id,
          kind: "KYC_REPORT",
          filename: `kyc-report-${new Date().toISOString().slice(0, 10)}.md`,
          mime: "text/markdown",
          sizeBytes: Buffer.byteLength(report, "utf8"),
          data: Buffer.from(report, "utf8").toString("base64"),
          notes: `Risk: ${riskLevel} (${source})`,
          uploadedBy: user.id,
        },
      }),
      prisma.client.update({
        where: { id: client.id },
        data: {
          kycStatus: verified ? "VERIFIED" : "PENDING",
          amlRisk: riskLevel,
        },
      }),
    ]);

    await writeAudit({
      companyId: user.companyId,
      actorId: user.id,
      action: "KYC_VERIFIED",
      entityType: "Client",
      entityId: client.id,
      before: { kycStatus: client.kycStatus, amlRisk: client.amlRisk },
      after: { kycStatus: verified ? "VERIFIED" : "PENDING", riskLevel, source, reportDocId: doc.id },
    });

    return { kycStatus: verified ? "VERIFIED" : "PENDING", riskLevel, source, reportDocId: doc.id };
  });
}
