import { NextRequest } from "next/server";
import { handle } from "@/lib/api";
import { prisma } from "@/lib/prisma";
import { requirePermission, AuthError } from "@/lib/auth";
import { conflictQuestionnaireSchema } from "@/lib/validation";
import { CONFLICT_QUESTIONS } from "@/lib/constants";
import { writeAudit } from "@/lib/audit";

export const dynamic = "force-dynamic";

// POST /api/clients/:id/conflict-check
// Full conflict procedure: the online checklist questionnaire + a name-overlap
// scan across all clients and matters. Produces a markdown report stored in
// the client file (ClientDocument, kind CONFLICT_REPORT) and sets the client's
// conflict status: any "yes" answer or any name match -> POTENTIAL, else CLEAR.
export async function POST(req: NextRequest, { params }: { params: { id: string } }) {
  return handle(async () => {
    const user = await requirePermission("client:manage");
    const input = conflictQuestionnaireSchema.parse(await req.json());

    const client = await prisma.client.findFirst({
      where: { id: params.id, companyId: user.companyId, deletedAt: null },
    });
    if (!client) throw new AuthError(404, "not_found");

    // Every checklist question must be answered.
    const answered = new Set(input.answers.map((a) => a.key));
    const missing = CONFLICT_QUESTIONS.filter((q) => !answered.has(q.key));
    if (missing.length) throw new AuthError(422, "questionnaire_incomplete");

    // Name-overlap scan (unchanged logic from v1).
    const tokens = client.name.toLowerCase().split(/\s+/).filter((w) => w.length >= 3);
    const [otherClients, matters] = await Promise.all([
      prisma.client.findMany({
        where: { companyId: user.companyId, deletedAt: null, id: { not: client.id } },
        select: { name: true },
      }),
      prisma.matter.findMany({
        where: { companyId: user.companyId, clientId: { not: client.id } },
        select: { name: true, client: { select: { name: true } } },
      }),
    ]);
    const candidates = [
      ...otherClients.map((c) => c.name),
      ...matters.map((m) => `${m.name} (${m.client.name})`),
    ];
    const matches = candidates.filter((n) => {
      const hay = n.toLowerCase();
      return tokens.some((tk) => hay.includes(tk));
    });

    const flaggedAnswers = input.answers.filter((a) => a.answer);
    const status = flaggedAnswers.length > 0 || matches.length > 0 ? "POTENTIAL" : "CLEAR";

    // Build the report (markdown, stored in the client file).
    const qLabel = new Map(CONFLICT_QUESTIONS.map((q) => [q.key, q.en]));
    const lines = [
      `# Conflict of Interest Report`,
      ``,
      `**Client:** ${client.name} (${client.type})`,
      `**Checked by:** ${user.fullName}`,
      `**Date:** ${new Date().toISOString().slice(0, 10)}`,
      `**Outcome:** ${status}`,
      ``,
      `## Checklist questionnaire`,
      ...input.answers.map(
        (a) =>
          `- ${qLabel.get(a.key) ?? a.key}: **${a.answer ? "YES" : "No"}**` +
          (a.details ? ` — ${a.details}` : ""),
      ),
      ``,
      `## Name-overlap scan (${matches.length} match${matches.length === 1 ? "" : "es"})`,
      ...(matches.length ? matches.slice(0, 20).map((m) => `- ${m}`) : ["- No overlaps found."]),
      ``,
      ...(input.notes ? [`## Notes`, input.notes, ``] : []),
      `---`,
      `Generated by Dentons KMN Finance — conflict procedure. ` +
        `A POTENTIAL outcome requires partner review before the matter proceeds.`,
    ];
    const report = lines.join("\n");

    const [, doc] = await prisma.$transaction([
      prisma.conflictCheck.create({
        data: {
          companyId: user.companyId,
          clientId: client.id,
          status,
          matches: matches.length ? JSON.stringify(matches.slice(0, 20)) : null,
          questionnaire: JSON.stringify(input.answers),
          notes: input.notes || null,
          checkedById: user.id,
        },
      }),
      prisma.clientDocument.create({
        data: {
          companyId: user.companyId,
          clientId: client.id,
          kind: "CONFLICT_REPORT",
          filename: `conflict-report-${new Date().toISOString().slice(0, 10)}.md`,
          mime: "text/markdown",
          sizeBytes: Buffer.byteLength(report, "utf8"),
          data: Buffer.from(report, "utf8").toString("base64"),
          uploadedBy: user.id,
        },
      }),
      prisma.client.update({ where: { id: client.id }, data: { conflictStatus: status } }),
    ]);

    await writeAudit({
      companyId: user.companyId,
      actorId: user.id,
      action: "CONFLICT_CHECK_RUN",
      entityType: "Client",
      entityId: client.id,
      after: { status, flaggedAnswers: flaggedAnswers.length, matches: matches.length, reportDocId: doc.id },
    });

    return { status, matches: matches.slice(0, 20), flagged: flaggedAnswers.length, reportDocId: doc.id };
  });
}
